import {
  Compass,
  HelpCircle,
  Lightbulb,
  Notebook,
  Sparkles,
  StickyNote,
  Tags,
  Undo2,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Single source of truth for the visual language of knowledge objects.
 * Every kind pairs a colour with an icon AND a label — colour is never the
 * only signal. Palette is deliberately restrained: one hue per kind, used as
 * border/text tint on outline badges and soft backgrounds, readable in both
 * light and dark mode.
 *
 *   topic          blue    — broad research area (landscape)
 *   concept        teal    — technical reference entry
 *   question       amber   — something unresolved
 *   misconception  rose    — a belief that turned out wrong (+ correction)
 *   correction     rose    — fixing something you or a summary got wrong
 *   idea           emerald — experiment idea / connection / application
 *   note           neutral — personal interpretation
 *   ai             violet  — AI-generated material (see AiBadge)
 */

export type KnowledgeObjectKind =
  "topic" | "concept" | "question" | "misconception" | "correction" | "idea" | "note" | "ai";

export interface KnowledgeObjectStyle {
  kind: KnowledgeObjectKind;
  label: string;
  icon: LucideIcon;
  /** Outline-badge tint: border + text colour. */
  badgeClass: string;
  /** Text-only tint (icons, counts). */
  textClass: string;
  /** Soft fill for cards/callouts that need more presence than a badge. */
  surfaceClass: string;
  description: string;
}

export const KNOWLEDGE_OBJECTS: Record<KnowledgeObjectKind, KnowledgeObjectStyle> = {
  topic: {
    kind: "topic",
    label: "Topic",
    icon: Tags,
    badgeClass: "border-blue-600/40 text-blue-700 dark:text-blue-400",
    textClass: "text-blue-700 dark:text-blue-400",
    surfaceClass: "border-blue-600/30 bg-blue-500/5",
    description: "A broad area of research — organises the landscape of your library.",
  },
  concept: {
    kind: "concept",
    label: "Concept",
    icon: Compass,
    badgeClass: "border-teal-600/40 text-teal-700 dark:text-teal-400",
    textClass: "text-teal-700 dark:text-teal-400",
    surfaceClass: "border-teal-600/30 bg-teal-500/5",
    description:
      "A technical reference entry: definition, mechanism, equations, applications, failure modes.",
  },
  question: {
    kind: "question",
    label: "Question",
    icon: HelpCircle,
    badgeClass: "border-amber-600/40 text-amber-700 dark:text-amber-400",
    textClass: "text-amber-700 dark:text-amber-400",
    surfaceClass: "border-amber-600/30 bg-amber-500/5",
    description: "Something you don't understand yet. Stays open until you resolve it.",
  },
  misconception: {
    kind: "misconception",
    label: "Misconception",
    icon: Lightbulb,
    badgeClass: "border-rose-600/40 text-rose-700 dark:text-rose-400",
    textClass: "text-rose-700 dark:text-rose-400",
    surfaceClass: "border-rose-600/30 bg-rose-500/5",
    description: "A belief you held that turned out wrong, recorded with its correction.",
  },
  correction: {
    kind: "correction",
    label: "Correction",
    icon: Undo2,
    badgeClass: "border-rose-600/40 text-rose-700 dark:text-rose-400",
    textClass: "text-rose-700 dark:text-rose-400",
    surfaceClass: "border-rose-600/30 bg-rose-500/5",
    description: "Fixes something you (or a summary) previously got wrong.",
  },
  idea: {
    kind: "idea",
    label: "Idea",
    icon: Zap,
    badgeClass: "border-emerald-600/40 text-emerald-700 dark:text-emerald-400",
    textClass: "text-emerald-700 dark:text-emerald-400",
    surfaceClass: "border-emerald-600/30 bg-emerald-500/5",
    description: "An experiment idea, connection, or possible application.",
  },
  note: {
    kind: "note",
    label: "Note",
    icon: StickyNote,
    badgeClass: "border-border text-muted-foreground",
    textClass: "text-muted-foreground",
    surfaceClass: "border-border bg-muted/30",
    description: "Your own interpretation, in your own words.",
  },
  ai: {
    kind: "ai",
    label: "AI-generated",
    icon: Sparkles,
    badgeClass: "border-violet-500/40 text-violet-700 dark:text-violet-400",
    textClass: "text-violet-700 dark:text-violet-400",
    surfaceClass: "border-violet-500/30 bg-violet-500/5",
    description: "Generated by AI from the paper — editable, and labelled until you edit it.",
  },
};

/** Personal-notes icon used on nav and dashboards (not a badge kind). */
export const PERSONAL_NOTES_ICON = Notebook;
